// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Polling App 2020', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginPositive', async function() {
    await driver.get("http://poll-app7-20200409.softacad.bg/login")
    await driver.findElement(By.id("usernameOrEmail")).sendKeys("tg4admin")
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.name("login")).click()
  })
  it('LoginLogout', async function() {
    await driver.get("http://poll-app7-20200409.softacad.bg/login")
    await driver.findElement(By.id("usernameOrEmail")).sendKeys("tg4admin")
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.name("login")).click()
    await driver.findElement(By.xpath("//span[contains(@class,\'oi oi-person\')]")).click()
    await driver.findElement(By.xpath("//button[contains(@name,\'logout-button\')]")).click()
  })
  it('Signup', async function() {
    await driver.get("http://poll-app7-20200409.softacad.bg/signup")
    await driver.findElement(By.xpath("//input[contains(@id,\'full-name\')]")).sendKeys("Tanya")
    await driver.findElement(By.xpath("//input[contains(@id,\'username\')]")).sendKeys("tanyalp")
    await driver.findElement(By.xpath("//input[contains(@id,\'email\')]")).sendKeys("tan.lp@abv.bg")
    await driver.findElement(By.xpath("//input[contains(@id,\'password\')]")).sendKeys("666666")
    await driver.findElement(By.xpath("//button[contains(@id,\'register\')]")).click()
  })
  it('CreateRandomPoll', async function() {
    await driver.get("http://poll-app7-20200409.softacad.bg/login")
    await driver.findElement(By.id("usernameOrEmail")).sendKeys("tg4admin")
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.name("login")).click()
    await driver.findElement(By.xpath("//a[@class=\"navbar-brand\"]")).click()
    vars["randomQuestion"] = await driver.executeScript("return Math.random().toString(36).substring(7);")
    vars["randomChoice1"] = await driver.executeScript("return Math.random().toString(36).substring(7);")
    vars["randomChoice2"] = await driver.executeScript("return Math.random().toString(36).substring(7);")
    await driver.findElement(By.xpath("//textarea")).sendKeys(vars["randomQuestion"])
    await driver.findElement(By.xpath("(//input)[1]")).sendKeys(vars["randomChoice1"])
    await driver.findElement(By.xpath("(//input)[2]")).sendKeys(vars["randomChoice2"])
    {
      const dropdown = await driver.findElement(By.xpath("//select[contains(@id,\'day\')]"))
      await dropdown.findElement(By.xpath("//option[. = '3']")).click()
    }
    await driver.findElement(By.xpath("(//button)[3]")).click()
  })
  it('CreatePollWithThreeChoices', async function() {
    await driver.get("http://poll-app7-20200409.softacad.bg/login")
    await driver.findElement(By.id("usernameOrEmail")).sendKeys("tg4admin")
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.name("login")).click()
    await driver.findElement(By.xpath("//a[@class=\"navbar-brand\"]")).click()
    await driver.findElement(By.xpath("//textarea")).sendKeys("What is your favourite TV show?")
    await driver.findElement(By.xpath("(//input)[1]")).sendKeys("Fargo")
    await driver.findElement(By.xpath("(//input)[2]")).sendKeys("Dexter")
    await driver.findElement(By.xpath("//button[@class=\'btn btn-outline-secondary\']")).click()
    await driver.findElement(By.xpath("//input[@placeholder=\'Choice 3\']")).sendKeys("True Detective")
    {
      const dropdown = await driver.findElement(By.xpath("//select[contains(@id,\'day\')]"))
      await dropdown.findElement(By.xpath("//option[. = '3']")).click()
    }
    await driver.findElement(By.xpath("(//button)[3]")).click()
  })
})
